### ISSUE TITLE
source strings are not showing for .js file in transifex 

### ISSUE THREAD

**Issue by Lungsangg** [transifex/openformats#311]
Hello, I am trying to link a .js file between a github repo and transifex project. Once the file is imported in transifex, when trying to translate, the source string (en) is not visible. Though number of string list is visible (in my case, its 15). Can you please let me know what might be the issue. 

this is my file content sample in .js format : 
```
define({
  "Indrajala": "",
  "Topics":"",
  "Community": "",
  "Donate": "",
  "Indrajala Notifications": "",
  "Library Online": "",
  "Recently Viewed" : "",
  "The Sefaria Library": "",
  "Indrajala Search": "",
  "Sefaria Account": "",
  "Notifcations": "",
  "New Additions to the Sefaria Library": "",
  "My Notes on Sefaria": "",
  "Texts & Source": "",
  "Moderator Tools": ""
});
```
this is the transifex.yaml file : (I think this one is working fine)
```
git:
  filters:
    - filter_type: dir
      file_format: REQUIREJS
      source_file_extension: .js
      source_language: en
      source_file_dir: locale_frontend/zh
      translation_files_expression: 'locale_frontend/zh/<lang>'
```
